version: '3'
volumes:
  node-modules:
services:
  app:
    build: .
    container_name: dev_express
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - node-modules:/app/node_modules
    working_dir: /app
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dev_express
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf